spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:13306/ryoko
spring.datasource.username=root
spring.datasource.password=ryoko
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true